destair.training.preprocessing_mt_data.yaml

quality trimming phase completed with instructions that encourage the user to use the interactive tour's "Next" and "Prev" buttons for following the training steps

Preprocessing mt data

---

tour_1a.yml
tour_1b.yml
tour_2a.yml
tour_3b.yml

added:
- tour block 1
- tour block 3
- tour block 3

Modular tours

---

tour_1a.yaml

- sample data loaded from github
- bubbles are not placed on the single parameter boxes due to lack of "id" elements, or unfortunate overlapping of the bubble with other parts of the interface that are required to be visible to understand the behavior of the tool
- FastQC bubbles contain comments from FastQC training material
- FastQC bubbles contain links to further explanation of plots
- Trim Galore! bubbles contain comments from Trim Galore! training material

added tour 1a with sample data from github

---

tour_1b.yaml

tour 1b implements tour 1a with the only difference of using Trimmomatic instead of Trim Galore!

added tour 1b

---

tour_1a.yaml
tour_1b.yaml

aligned the content of tour_1a and tour_1b

minor content reorganisation

---

tour_1a.yaml
tour_1b.yaml

Corrected the explanation of each FastQC plot for the tours 1a and 1b

Fastqc explanations

---

dgea_tour_1a.yaml
dgea_tour_1b.yaml
dgea_tour_1c.yaml
dgea_tour_1d.yaml

Added support for positioning tour bubbles on element attribute tour_id.
This involves tours:
- dgea_tour_1a
- dgea_tour_1b
- dgea_tour_1c
- dgea_tour_1d

Added support for positioning tour bubbles on element attribute tour_id

---

dgea_tour_1a.html
dgea_tour_1a.yaml
dgea_tour_1b.html
dgea_tour_1b.yaml
dgea_tour_1c.html
dgea_tour_1c.yaml
dgea_tour_1d.html
dgea_tour_1d.yaml
dgea_tour_2a.html
dgea_tour_2a.yaml
dgea_tour_2b.html
dgea_tour_2b.yaml
dgea_tour_2c.html
dgea_tour_2c.yaml
dgea_tour_2d.html
dgea_tour_2d.yaml

Renamed tours and helper pages according to their tools in lexicographical order

Lexicographical order

---

dgea_tour_1a.html
dgea_tour_1b.html
dgea_tour_1c.html
dgea_tour_1d.html
dgea_tour_2a.html
dgea_tour_2b.html
dgea_tour_2c.html
dgea_tour_2d.html
dgea_tour_3a.html
dgea_tour_3b.html

- Added target="_blank" attribute to HTML help pages to avoid open reference links inside the iframe
- Changed link to online papers with DOI

Help pages

---

README.md

Added instructions to test new atoms using the interactive plugin

Added instructions to test new atoms using the interactive plugin

---

destair_linker1.html
destair_linker2.html
destair_linker3.html

- Edited linker descriptions
- Fixed HTML formatting

Edited linker descriptions

---

bs_tour_2b.yaml
bs_tour_2c.yaml
bs_tour_2d.yaml

Added alternative atoms for BS/RRBS-Seq analysis:
- bs_tour_1b
- bs_tour_1c
- bs_tour_1d

Added alternative atoms

---

bs_tour_2a.html
bs_tour_2b.html
bs_tour_2c.html
bs_tour_2d.html

Added:
- bs_tour_2a.html
- bs_tour_2b.html
- bs_tour_2c.html
- bs_tour_2d.html

added help descriptions

---

bs_tour_2a.html
bs_tour_2b.html
bs_tour_2c.html
bs_tour_2d.html
dgea_tour_2a.html
dgea_tour_2b.html
dgea_tour_2c.html
dgea_tour_2d.html

Fixed FASTQ format description

fixed format description

---

dgea_tour_3a.yaml

fixed yaml format

---

bs_tour_3b.html
bs_tour_3c.html
bs_tour_3d.html
bs_tour_3e.html

Added atoms descriptions:
- bs_tour_3b.html
- bs_tour_3c.html
- bs_tour_3d.html
- bs_tour_3e.html

Added atoms descriptions

---

dgea_tour_3b.yaml
dgea_tour_3c.yaml
dgea_tour_3d.yaml

Modified tour contents and locations for:
- dgea_tour_3b
- dgea_tour_3c
- dgea_tour_3d

Modified tour content and locations

---

destair_linker3.html
destair_linker3.yaml
dgea_pe_tour_1a.yaml

- Added new .yaml linker for dgea (paired-end data) tours
- Added new .html linker help for dgea (paired-end data) tours
- Added new tour *dgea_pe_tour_1a*

added dgea paired-end tour 1a

---

dgea_pe_tour_1a.yaml

fixed typo in dgea_pe_tour_1a.yaml

---

dgea_pe_tour_3d.yaml

Added dgea_pe_tour_3d using new version of STAR

added dgea_pe_tour_3d

---

dgea_tour_3d.yaml

Updated dgea_tour_3d with new version of STAR

updated dgea_tour_3d with new version of STAR

---

dgea_se_1a.yaml

updated dgea_se_1a.yaml

---

dgea_pe_1a.yaml

updated dgea_pe_1a.yaml

---

bs_pe_1a.html
destair_linker1.html
destair_linker1.yaml
destair_linker2.html
destair_linker2.yaml
destair_linker3.html
destair_linker3.yaml
destair_template.html
dgea_pe_1a.html
dgea_se_1a.html

- Reordered linkers to list:
- DGEA SE
- DGEA PE
- RRBS/BS PE
- Updated linker descriptions to always list if PE or SE
- Aligned the help page description of bs_pe_1a with those of dgea_se_1a and dgea_pe_1a

Updated descriptions

---

dgea_se_2a.yaml
dgea_se_2b.yaml
dgea_se_2c.yaml
dgea_se_2d.yaml

- Removed user input from dgea_se_2a
- Removed user input from dgea_se_2b
- Removed user input from dgea_se_2c
- Extended parameterization section of dgea_se_2d
- Aligned indentations and wording

Removed user input

---

dgea_se_2a.yaml
dgea_se_2b.yaml
dgea_se_2c.yaml
dgea_se_2d.yaml
dgea_se_3a.yaml
dgea_se_3b.yaml
dgea_se_3c.yaml
dgea_se_3d.yaml
dgea_se_4a.yaml
dgea_se_4b.yaml

Added the experimental setup indication in the headers of the DGEA SE atoms

Updated headers

---

dgea_pe_4a.yaml
dgea_pe_4b.yaml

- Added comments for better readability
- Spelling fixes
- Repositioned dialogs

Better readability

---

bs_pe_2a.html
bs_pe_3a.html
dgea_pe_2a.html
dgea_pe_2b.html
dgea_pe_2c.html
dgea_pe_2d.html
dgea_pe_3a.html
dgea_pe_3b.html
dgea_pe_3d.html
dgea_pe_4a.html
dgea_pe_4b.html
dgea_se_2a.html
dgea_se_2b.html
dgea_se_2c.html
dgea_se_2d.html
dgea_se_3a.html
dgea_se_3b.html
dgea_se_3c.html
dgea_se_3d.html
dgea_se_4a.html
dgea_se_4b.html

- Added missing tools descriptions
- Uniformed indentation

fixed help sections

---

README.md

Added a table for each type of analysis to show the contributed atoms so far

Added contributed atoms
